### ISSUE TITLE
stdout lost if both `stderr_file` and `stdout_file` are set

### ISSUE THREAD

**Issue by lucasfernog** [oconnor663/duct.rs#102]
I use your amazing libraries on the [tauri repo](https://github.com/tauri-apps/tauri/blob/dev/core/tauri/src/api/process/command.rs) and I'm having an issue because I set both `stderr` and `stdout` pipes, and I lose some stdout information in this case.

The command I'm running for this test is `curl --progress-bar http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4 -o file.mp4`. Right now I'm using shared_child+os_pipe, but I also tried using duct directly but I didn't fix this problem for me.

Snippet using shared_child+os_pipe:
```rust
use std::process::Command;
use os_pipe::pipe;
use shared_child::SharedChild;

let mut command = std::process::Command::new("curl");
command.args(["--progress-bar", "http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4", "-o", "test.mp4"]);
let (stdout_reader, stdout_writer) = pipe()?;
let (stderr_reader, stderr_writer) = pipe()?;
let (stdin_reader, stdin_writer) = pipe()?;
command.stdout(stdout_writer);
command.stderr(stderr_writer);
command.stdin(stdin_reader);

let shared_child = SharedChild::spawn(&mut command)?;

std::thread::spawn(move || {
  let reader = BufReader::new(stdout_reader);
  for line in reader.lines() {
    println!("stdout: {:?}", line);
  }
});

std::thread::spawn(move || {
  let reader = BufReader::new(stderr_reader);
  for line in reader.lines() {
    println!("stderr: {:?}", line);
  }
});

std::thread::spawn(move || {
  let _ = match shared_child.wait() {
    Ok(status) => {
      println!("finished with status {:?}", status);
    }
    Err(e) => {
      println!("error: {}", e);
    }
  };
});
```

Using duct:
```rust
use duct::cmd;
use os_pipe::pipe;

let (stdout_reader, stdout_writer) = pipe()?;
let (stderr_reader, stderr_writer) = pipe()?;
let (stdin_reader, stdin_writer) = pipe()?;

let mut expression = cmd(self.program, self.args);
expression = expression.stdout_file(stdout_writer);
expression = expression.stderr_file(stderr_writer);
expression = expression.stdin_file(stdin_reader);

let handle = expression.start()?;

std::thread::spawn(move || {
  let reader = BufReader::new(stdout_reader);
  for line in reader.lines() {
    println!("stdout: {:?}", line);
  }
});

std::thread::spawn(move || {
  let reader = BufReader::new(stderr_reader);
  for line in reader.lines() {
    println!("stderr: {:?}", line);
  }
});

std::thread::spawn(move || {
  let _ = match handle.wait() {
    Ok(status) => {
      println!("finished with status {:?}", status);
    }
    Err(e) => {
      println!("error: {}", e);
    }
  };
});
```

Removing `command.stderr()` and `expression.stderr_file()` calls fixes the problem and I get the stdout messages again.

**Comment by oconnor663** [comment]
Could you give me a little more detail about the output you see, vs the output you expected / wanted to see?

My first guess in cases like this is that the program is detecting whether it's talking to a terminal (specifically a "tty"), and then it's changing its own output as a result. We might be able to test this by doing `>`, `2>`, and `<` redirections in the terminal.

**Comment by lucasfernog** [comment]
I don't receive any output on the reader.lines() call, and it should have several lines printed to stdout (it's the progress bar from curl), it just works if I only bind the stdout pipe.

**Comment by oconnor663** [comment]
Ok I think I understand the issue here. `curl` actually *is* writing to stderr, but the issue is that it isn't writing any *newlines* to stderr, so your `.lines()` iterator never actually yields anything. (Instead it just keeps buffering and buffering one giant line, waiting forever for it to finish.) What `curl` is doing is writing a "carriage return" (the `'\r'` character) to send the cursor back to the left, so that it can redraw the line. You can see this output if you read stderr one byte at a time, or if you use `read_until` with `'\r'` like this:

```rust
let mut reader = BufReader::new(stderr_reader);
let mut buf = Vec::new();
loop {
    buf.clear();
    let n = reader.read_until(b'\r', &mut buf).unwrap();
    if n == 0 {
        break;
    }
    println!("stderr: {:?}", String::from_utf8_lossy(&buf));
}
```

---

If you'll forgive me, I want to give you some general advice about asking questions like this in the future. Even after your clarification, it wasn't easy for me to understand what you were seeing or what you expected to see. For example, when you say "it just works", I _think_ you meant "I see output in the terminal", but you might also have meant "my stdout loop reads lines". The easiest way to avoid this kind of misunderstanding is to include exactly what your program prints in your bug report, and also what you expected/wanted it to print.

Also, I'm very glad you provided code samples, but your code samples aren't runnable. It looks like they've been taken out of context from a larger program. For example, there are `self` variables in there that won't compile. It took several minutes of fiddling to get those to run. When you can, please try to make sure the code samples you provide can run on other people's machines without modification.

**Comment by lucasfernog** [comment]
Sorry about that, I agree I could've explained it better and I indeed forgot to update the second example. I'll take a look at your suggestion, weird that it worked when only piping to stdout.

**Comment by oconnor663** [comment]
> weird that it worked when only piping to stdout

If I'm understanding correctly, the explanation is that `curl` is printing progress only to stderr, and not printing anything to stdout. So capturing stdout is a red herring; it has no effect. When you avoid capturing stderr, it just goes to the terminal like normal, and you see the result. But when you do capture stderr, you're not going to see anything in the terminal unless you print it yourself. (Which your example code wasn't doing, because of the `.lines()` issue.) Does that make sense?
