### ISSUE TITLE
Command with regex

### ISSUE THREAD

**Issue by rmonteil** [oconnor663/duct.rs#59]
Hi :slightly_smiling_face: 

First, thanks for your work, it's really useful!

I have a problem executing commands containing a regular expression...
I'd like to execute a command which looks like that:
```shell
ps cax | grep "myprocess$"
```
I tried different alternatives of:
```rust
let stdout = cmd!("ps", "cax")
    .pipe(cmd!("grep", "-e", "'myprocess$'"))
    .read()
    .unwrap();
println!("stdout: {:?}", stdout);
```
But couldn't make it work... I always get an error like the one below:
```shell
Custom { kind: Other, error: StringError("command [\"grep\", \"-e\", \"\\\'myprocess$\\\'\"] exited with code1") }
```

Did I miss something, or it's just not possible at the moment with `duct`?

Thank you!

**Comment by oconnor663** [comment]
There's probably two things you need to tweak.

First, because duct isn't going through a shell, you don't need to add any special quoting for shell special characters. When you write `"'myprocess$'"`, what's happening is that those inner `'` characters are getting passed through as literals, and `grep` is seeing them and trying to match on them. Instead, just use the Rust string `"myprocess$"`. The `$` will get preserved, and grep will see `myprocess$`.

Second, duct by default is strict with exit codes. `run()` and `read()` will return errors when the exit code is non-zero, and `unwrap()` will turn those errors into panics. If you try `echo foo | grep bar; echo $?` in your shell, you'll see that `grep` returns exit code 1 when it doesn't find any matches. If you don't care about the error code, you can use duct's `unchecked` method to ignore the error, and maybe just check whether the string is empty. If you do want to look at the code, you'll need to use `unchecked` and then also switch from `read` to `run`, which includes the error code in the struct it returns.

**Comment by oconnor663** [comment]
Awesome!
